# Values for Argo CD Application
global:
  domain: lab.grove.local

configs:
  params:
    server.insecure: true
  repositories:
    kubernetes-lab-repo:
      url: https://github.com/mimartin12/kuberentes-lab
      name: kubernetes-lab
      type: git

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true