# admin
admin:
  create: true
  username: admin
  password: password

ingress:
  enabled: true
  host: vcluster.idkthisisademo.lol
  name: vcluster-platform-ingress
  ingressClass: cilium

audit:
  enableSideCar: true
  level: 1

config:
  loftHost: "https://vcluster-platform.example"