# admin
admin:
  create: true
  username: admin
  password: password

ingress:
  enabled: true
  host: vcluster.idkthisisademo.lol
  name: vcluster-platform-ingress
  ingressClass: cilium
  annotation:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  tls:
    enabled: true
    secretName: vcluster-platform-tls

audit:
  enableSideCar: true
  level: 1

config:
  loftHost: "https://vcluster-platform.example"