apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-the-apps
  namespace: argocd
  labels:
    name: all-the-apps
    stage: bootstrapping
spec:
  project: default
  source:
    repoURL: https://github.com/mimartin12/kuberentes-lab.git
    targetRevision: HEAD
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "1m"
