apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qwen-coder-interceptor
  namespace: keda
spec:
  ingressClassName: cilium
  rules:
    - host: qwen-coder-kserve-test.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keda-add-ons-http-interceptor-proxy
                port:
                  number: 8080
