apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
  labels:
    name: nvidia-device-plugin
    stage: infrastructure
spec:
  project: default
  sources:
    - repoURL: https://nvidia.github.io/k8s-device-plugin
      targetRevision: 0.17.0
      chart: nvidia-device-plugin
      helm:
        valueFiles:
          - $values/argocd/applications/values/nvidia-device-plugin.yaml
    - repoURL: https://github.com/mimartin12/kuberentes-lab
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
