apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw-operator
  namespace: argocd
  labels:
    name: openclaw-operator
    stage: application
spec:
  project: default
  sources:
  - repoURL: https://github.com/mimartin12/openclaw-k8s-operator
    targetRevision: HEAD
    path: charts/openclaw-operator
    helm:
      valueFiles:
        - $values/argocd/applications/values/openclaw-operator.yaml
      ignoreMissingValueFiles: true
  - repoURL: https://github.com/mimartin12/kubernetes-lab
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/mimartin12/kubernetes-lab
    targetRevision: HEAD
    path: argocd/applications/manifests/openclaw-agents
  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true